### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by AgustinV08** [apeiro-tech/conekta_flutter#5]
Crashes on android after calling createCardToken function

**Comment by aosorio-avilez** [comment]
Could you provide more info?

**Comment by mugveiga** [comment]
```
E/AndroidRuntime(19572): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(19572): Process: net.boomcredit.mobile.android, PID: 19572
E/AndroidRuntime(19572): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(19572): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(19572): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(19572): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(19572): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(19572): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime(19572): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(19572): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(19572): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(19572): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/logging/LogFactory;
E/AndroidRuntime(19572): 	at org.apache.http.impl.client.AbstractHttpClient.<init>(AbstractHttpClient.java:182)
E/AndroidRuntime(19572): 	at org.apache.http.impl.client.DefaultHttpClient.<init>(DefaultHttpClient.java:150)
E/AndroidRuntime(19572): 	at io.conekta.conektasdk.Connection$Task.doInBackground(Connection.java:48)
E/AndroidRuntime(19572): 	at io.conekta.conektasdk.Connection$Task.doInBackground(Connection.java:43)
E/AndroidRuntime(19572): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(19572): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(19572): 	... 4 more
E/AndroidRuntime(19572): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.LogFactory" on path: DexPathList[[zip file 
```
